import { addDays, format } from 'date-fns'
import type { Item } from './types'
import { uid } from './utils'

const iso = (offsetDays: number) =>
  format(addDays(new Date(), offsetDays), 'yyyy-MM-dd')

const base = (): Pick<Item, 'currency' | 'status' | 'priceHistory'> => ({
  currency: 'USD',
  status: 'active',
  priceHistory: [],
})

export function sampleItems(): Item[] {
  const now = Date.now()
  const mk = (
    partial: Omit<Item, 'id' | 'createdAt' | 'updatedAt' | 'currency' | 'status' | 'priceHistory'> &
      Partial<Pick<Item, 'currency' | 'status' | 'priceHistory'>>,
  ): Item => ({
    id: uid(),
    createdAt: now,
    updatedAt: now,
    ...base(),
    ...partial,
  })

  return [
    mk({
      title: 'PG&E electricity bill',
      category: 'utility',
      provider: 'PG&E',
      amount: 148.32,
      dueDate: iso(-3),
      recurrence: 'monthly',
      accountNumber: '4820-119-3',
      autoPay: false,
      action: 'pay',
      actionNote: 'Past due — pay to avoid a late fee.',
    }),
    mk({
      title: 'Aetna dental premium',
      category: 'medical',
      provider: 'Aetna',
      amount: 42.0,
      dueDate: iso(2),
      recurrence: 'monthly',
      accountNumber: 'AET-77120',
      autoPay: false,
      action: 'pay',
    }),
    mk({
      title: 'Geico auto insurance',
      category: 'insurance',
      provider: 'Geico',
      amount: 712.4,
      dueDate: iso(6),
      recurrence: 'quarterly',
      accountNumber: 'GEC-4471902',
      autoPay: true,
      action: 'renew',
      actionNote: 'Premium jumped this term — confirm why before it auto-renews.',
      priceHistory: [
        { date: iso(-180), amount: 604.1 },
        { date: iso(-2), amount: 712.4 },
      ],
    }),
    mk({
      title: 'Netflix subscription',
      category: 'subscription',
      provider: 'Netflix',
      amount: 22.99,
      dueDate: iso(9),
      recurrence: 'monthly',
      autoPay: true,
      action: 'none',
      usage: 'often',
      priceHistory: [
        { date: iso(-365), amount: 15.49 },
        { date: iso(-30), amount: 22.99 },
      ],
    }),
    mk({
      title: 'Spotify Premium',
      category: 'subscription',
      provider: 'Spotify',
      amount: 11.99,
      dueDate: iso(14),
      recurrence: 'monthly',
      autoPay: true,
      action: 'none',
      usage: 'often',
    }),
    mk({
      title: 'Apple Music',
      category: 'subscription',
      provider: 'Apple Music',
      amount: 10.99,
      dueDate: iso(18),
      recurrence: 'monthly',
      autoPay: true,
      action: 'review',
      actionNote: 'Overlaps with Spotify — pick one?',
      usage: 'rarely',
    }),
    mk({
      title: 'Planet Fitness membership',
      category: 'subscription',
      provider: 'Gym membership',
      amount: 24.99,
      dueDate: iso(21),
      recurrence: 'monthly',
      accountNumber: 'PF-88213',
      autoPay: true,
      action: 'review',
      usage: 'rarely',
    }),
    mk({
      title: 'Rent — Maple Street apt',
      category: 'housing',
      provider: 'Maple Street Property Mgmt',
      amount: 2150,
      dueDate: iso(11),
      recurrence: 'monthly',
      autoPay: false,
      action: 'pay',
    }),
    mk({
      title: 'Dentist cleaning',
      category: 'appointment',
      provider: 'Bright Smiles Dental',
      amount: null,
      dueDate: iso(4),
      recurrence: 'none',
      autoPay: false,
      action: 'call',
      actionNote: 'Confirm the appointment time.',
    }),
    mk({
      title: 'MacBook AppleCare warranty',
      category: 'warranty',
      provider: 'Apple',
      amount: null,
      dueDate: iso(40),
      recurrence: 'none',
      accountNumber: 'AC-2291-7761',
      autoPay: false,
      action: 'review',
      actionNote: 'Coverage expires soon — decide whether to extend.',
    }),
    mk({
      title: 'Property tax — 2nd installment',
      category: 'tax',
      provider: 'County Treasurer',
      amount: 1840.55,
      dueDate: iso(52),
      recurrence: 'yearly',
      accountNumber: 'APN 072-118-04',
      autoPay: false,
      action: 'pay',
    }),
    mk({
      title: 'Adobe Creative Cloud',
      category: 'subscription',
      provider: 'Adobe Creative Cloud',
      amount: 59.99,
      dueDate: iso(26),
      recurrence: 'monthly',
      autoPay: true,
      action: 'none',
      usage: 'sometimes',
    }),
    mk({
      title: 'Car loan payment',
      category: 'loan',
      provider: 'Chase Auto',
      amount: 389.0,
      dueDate: iso(15),
      recurrence: 'monthly',
      accountNumber: 'CH-AUTO-55190',
      autoPay: true,
      action: 'none',
    }),
    // a couple resolved items so the recap has history
    mk({
      title: 'Comcast internet',
      category: 'utility',
      provider: 'Xfinity',
      amount: 79.99,
      dueDate: iso(-6),
      recurrence: 'monthly',
      autoPay: true,
      action: 'none',
      status: 'resolved',
      resolvedAt: now - 1000 * 60 * 60 * 24 * 4,
    }),
  ]
}
